### PR TITLE
Use session to work with new CSRF check in 2.176.3+

### PR DESCRIPTION
**Pull request by jetersen**
After 2.176.3 security advisory it is suggested to reuse the session to further validate against CSRF.

See https://jenkins.io/security/advisory/2019-08-28/

### CODE REVIEW

**Comment by rasmusjelsgaard** [comment]
Seems like the tests are not passing atm :sweat: any idea what caused it?

**Comment by jetersen** [comment]
Most likely caused by me not updating the tests.

So the $script:sessionByUser is empty :)

**Comment by rasmusjelsgaard** [comment]
Could you fix the tests, please 🙏

**Comment by jetersen** [comment]
No, this is a won't do as PowerShell's http client does the magic 😆

**Pull request closed without merging**
